name: CNN
channels:
  - defaults
dependencies:
  - python=3.12
  - kagglehub==0.3.6
  - numpy==2.2
  - rich==13.9.4
  - scipy==1.14
  - nbformat==5.10.4
  - ipykernel==6.29.3
  - pillow==11.0.0

  - pip:
    - -e .
