name: CNN
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.5
  # ipython stuff
  - nbformat==5.10.4
  - ipykernel==6.29.3
  - ipywidgets==7.8.5

  # - kagglehub==0.3.6
  # - rich==13.9.4
  - pandas==2.2.3
  - plotly==6.0.1
  - numpy==2.1.3
  # - python-kaleido
  - cupy==13.4.1
  
  - pip
  - pip:
    - -e .
