name: CNN
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - kagglehub==0.3.6
  - numpy==2.1.3
  - rich==13.9.4
  - scipy==1.14
  - nbformat==5.10.4
  - ipykernel==6.29.3
  - pillow==11.0.0
  - pandas==2.2.3
  - plotly==5.24.1
  - ipywidgets==7.8.5
  - numba==0.61.0
  - pip
  - pip:
    - -e .
